import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Server Setup',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'server-setup' },
      ],
    },
    {
      type: 'category',
      label: 'Netzwerk & Zugriff',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'network-and-access' },
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'docker' },
      ],
    },
    {
      type: 'category',
      label: 'Anwendungen mit Docker',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'apps-docker' },
      ],
    },
    {
      type: 'category',
      label: 'Anwendungen ohne Docker',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'apps-wo-docker' },
      ],
    },
    {
      type: 'category',
      label: 'Backups & Snapshots',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'backups-and-snapshots' },
      ],
    },
    {
      type: 'category',
      label: 'Monitoring & Logging',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'monitoring-and-logging' },
      ],
    },
    {
      type: 'category',
      label: 'Performance & Optimierung',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'performance-and-improvement' },
      ],
    },
    {
      type: 'category',
      label: 'Best Practices & Sicherheit',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'best-practices-and-security' },
      ],
    },
    {
      type: 'category',
      label: 'Snippets & Referenzen',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'snippets' },
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'faq' },
      ],
    },
  ],
};

export default sidebars;
